"""Orchestrator generator — coordinates all generators to produce a complete workflow."""

from __future__ import annotations

from pathlib import Path

from architect.generators.approval_tool_gen import generate_approval_tools
from architect.generators.model_gen import generate_model
from architect.generators.pipeline_tool_gen import generate_pipeline_tools
from architect.generators.repo_gen import generate_repository
from architect.generators.schema_gen import generate_schema
from architect.generators.serialize_gen import generate_serialize
from architect.generators.tool_gen import generate_tools
from architect.primitives.workflow import WorkflowDefinition


def generate_workflow(
    workflow: WorkflowDefinition, base_output_dir: Path | None = None
) -> Path:
    """Generate all code for a workflow definition.

    Creates a directory per entity under ``base_output_dir / workflow.slug``
    with models, schemas, serialisation helpers, repository and MCP tools.
    A top-level ``_tools_registry.py`` wires every entity's ``register()``
    into a single ``register_all_tools(mcp)`` entry-point.

    Returns the path to the generated workflow directory.
    """
    if base_output_dir is None:
        base_output_dir = Path(__file__).parent.parent / "generated"

    workflow_dir = base_output_dir / workflow.slug
    workflow_dir.mkdir(parents=True, exist_ok=True)

    # Workflow-level __init__.py
    init_content = (
        "# AUTO-GENERATED by The Architect -- do not edit\n"
        f'__workflow_slug__ = "{workflow.slug}"\n'
    )
    (workflow_dir / "__init__.py").write_text(init_content)

    generated_entities: list[str] = []

    for entity in workflow.entities:
        entity_dir = workflow_dir / entity.name
        entity_dir.mkdir(parents=True, exist_ok=True)

        # Entity-level __init__.py
        (entity_dir / "__init__.py").write_text(
            "# AUTO-GENERATED by The Architect -- do not edit\n"
        )

        generate_model(entity, entity_dir)
        generate_schema(entity, entity_dir)
        generate_serialize(entity, entity_dir)
        generate_repository(entity, entity_dir)
        generate_tools(entity, entity_dir)

        generated_entities.append(entity.name)

    # Pipeline transition tools
    has_pipelines = bool(workflow.pipelines)
    if has_pipelines:
        generate_pipeline_tools(workflow.pipelines, workflow.slug, workflow_dir)

    # Approval tools (approve/reject/list_pending)
    has_dispatchers = bool(workflow.dispatchers)
    has_approval_gates = any(
        t.approval_required for p in workflow.pipelines for t in p.transitions
    )
    generate_approvals = has_dispatchers or has_approval_gates
    if generate_approvals:
        generate_approval_tools(workflow.slug, workflow_dir)

    # Top-level tools registry
    _generate_tools_registry(
        workflow, workflow_dir, generated_entities, has_pipelines, generate_approvals,
    )

    return workflow_dir


def _generate_tools_registry(
    workflow: WorkflowDefinition,
    workflow_dir: Path,
    entity_names: list[str],
    has_pipelines: bool = False,
    has_approvals: bool = False,
) -> Path:
    """Generate ``_tools_registry.py`` that registers all CRUD, pipeline, and custom tools."""
    lines = [
        "# AUTO-GENERATED by The Architect -- do not edit",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
        "",
        "def register_all_tools(mcp: Any) -> None:",
        '    """Register all CRUD, pipeline, approval, and custom tools for this workflow."""',
    ]

    has_content = False

    for name in entity_names:
        has_content = True
        lines.append(
            f"    from architect.generated.{workflow.slug}.{name}"
            f".tools import register as register_{name}"
        )
        lines.append(f"    register_{name}(mcp)")
        lines.append("")

    if has_pipelines:
        has_content = True
        lines.append(
            f"    from architect.generated.{workflow.slug}"
            f"._pipeline_tools import register as register_pipelines"
        )
        lines.append(f"    register_pipelines(mcp)")
        lines.append("")

    if has_approvals:
        has_content = True
        lines.append(
            f"    from architect.generated.{workflow.slug}"
            f"._approval_tools import register as register_approvals"
        )
        lines.append(f"    register_approvals(mcp)")
        lines.append("")

    custom_tools = [t for t in workflow.tools if t.kind == "custom"]
    for i, tool in enumerate(custom_tools):
        has_content = True
        module_path = tool.dotpath
        alias = f"register_custom_{i}"
        lines.append(f"    from {module_path} import register as {alias}")
        lines.append(f"    {alias}(mcp)")
        lines.append("")

    if not has_content:
        lines.append("    pass")

    content = "\n".join(lines) + "\n"
    output_path = workflow_dir / "_tools_registry.py"
    output_path.write_text(content)
    return output_path
